from __future__ import annotations

from dotenv import load_dotenv
load_dotenv()

import json
import logging
import os
from contextlib import contextmanager
from typing import Generator

import psycopg2
import psycopg2.extras
from pgvector.psycopg2 import register_vector
logger = logging.getLogger(__name__)

DATABASE_URL = os.getenv("DATABASE_URL")
if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL is not set")


# ---------------------------------------------------------------------------
# Connection
# ---------------------------------------------------------------------------

def get_connection(register_vectors: bool = True):
    """
    Open a new psycopg2 connection to Neon.
    Always use via get_db() context manager — never call directly.
    """
    conn = psycopg2.connect(DATABASE_URL)
    if register_vectors:
        register_vector(conn)   # enables pgvector types on this connection
    return conn


@contextmanager
def get_db(register_vectors: bool = True) -> Generator:
    """
    Context manager that yields a connection and commits on success,
    rolls back on any exception, and always closes the connection.

    Usage:
        with get_db() as conn:
            with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
                cur.execute("SELECT ...")
    """
    conn = get_connection(register_vectors=register_vectors)
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# Schema creation
# ---------------------------------------------------------------------------

SCHEMA_SQL = """
-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- repos: one row per ingested GitHub repository
CREATE TABLE IF NOT EXISTS repos (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    github_url  TEXT NOT NULL UNIQUE,
    name        TEXT,                    -- owner/repo extracted from URL
    status      TEXT NOT NULL DEFAULT 'pending',
                                         -- pending | ingesting | ready | failed
    phase       TEXT NOT NULL DEFAULT 'pending',
                                         -- current ingestion phase for polling UI
    error       TEXT,                    -- error message if status=failed
    chunk_count INT DEFAULT 0,
    cluster_tree JSONB,
    created_at  TIMESTAMPTZ DEFAULT now(),
    updated_at  TIMESTAMPTZ DEFAULT now()
);

-- chunks: one row per code/doc/config chunk
CREATE TABLE IF NOT EXISTS chunks (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    repo_id        UUID NOT NULL REFERENCES repos(id) ON DELETE CASCADE,
    file_path      TEXT NOT NULL,
    file_type      TEXT NOT NULL,        -- code | config | doc
    language       TEXT,                 -- python | typescript | go | etc.
    raw_code       TEXT NOT NULL,
    summary        TEXT,                 -- generated by Gemini
    start_line     INT,
    end_line       INT,
    loc            INT,
    is_split       BOOLEAN DEFAULT FALSE,
    chunk_index    INT DEFAULT 0,
    created_at     TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_chunks_repo_id ON chunks(repo_id);
CREATE INDEX IF NOT EXISTS idx_chunks_file_path ON chunks(repo_id, file_path);

-- vectors: one row per chunk, holds both embedding vectors
CREATE TABLE IF NOT EXISTS vectors (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    chunk_id        UUID NOT NULL REFERENCES chunks(id) ON DELETE CASCADE,
    repo_id         UUID NOT NULL,
    domain_id       UUID,                -- set after clustering
    summary_vector  vector(1536),         -- Gemini embedding-001
    code_vector     vector(1536),        -- Voyage voyage-code-2
    created_at      TIMESTAMPTZ DEFAULT now()
);

-- HNSW indexes for fast approximate nearest neighbour search
CREATE INDEX IF NOT EXISTS idx_summary_vector
    ON vectors USING hnsw (summary_vector vector_cosine_ops);

CREATE INDEX IF NOT EXISTS idx_code_vector
    ON vectors USING hnsw (code_vector vector_cosine_ops);

CREATE INDEX IF NOT EXISTS idx_vectors_repo_id   ON vectors(repo_id);
CREATE INDEX IF NOT EXISTS idx_vectors_domain_id ON vectors(domain_id);

-- domains: recursive cluster hierarchy
CREATE TABLE IF NOT EXISTS domains (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    repo_id     UUID NOT NULL REFERENCES repos(id) ON DELETE CASCADE,
    parent_id   UUID REFERENCES domains(id) ON DELETE CASCADE,
    label       TEXT NOT NULL,           -- e.g. "Authentication"
    summary     TEXT,                    -- one-line description from Gemini
    level       INT NOT NULL DEFAULT 0,  -- 0 = top level, 1 = submap, etc.
    chunk_ids   UUID[],                  -- chunks that belong to this domain
    created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_domains_repo_id   ON domains(repo_id);
CREATE INDEX IF NOT EXISTS idx_domains_parent_id ON domains(parent_id);

-- repo_ingest_log: rolling IP quota for public demo usage
CREATE TABLE IF NOT EXISTS repo_ingest_log (
    id          SERIAL PRIMARY KEY,
    ip_address  TEXT        NOT NULL,
    repo_id     TEXT        NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ingest_log_ip_day
    ON repo_ingest_log (ip_address, ingested_at);

ALTER TABLE repos ADD COLUMN IF NOT EXISTS phase TEXT NOT NULL DEFAULT 'pending';
"""


def create_schema() -> None:
    """Run schema creation SQL — safe to call multiple times (IF NOT EXISTS)."""
    with get_db(register_vectors=False) as conn:
        with conn.cursor() as cur:
            cur.execute(SCHEMA_SQL)
    logger.info("schema created / verified")


# ---------------------------------------------------------------------------
# Repo helpers
# ---------------------------------------------------------------------------

def create_repo(github_url: str, name: str) -> str:
    """Insert a new repo row and return its UUID."""
    with get_db() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO repos (github_url, name, status)
                VALUES (%s, %s, 'pending')
                ON CONFLICT (github_url) DO UPDATE
                    SET name = EXCLUDED.name, updated_at = now()
                RETURNING id
                """,
                (github_url, name),
            )
            return str(cur.fetchone()[0])


def set_repo_status(
    repo_id: str,
    status: str,
    error: str | None = None,
    phase: str | None = None,
) -> None:
    next_phase = phase or status
    with get_db() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                UPDATE repos
                SET status = %s, phase = %s, error = %s, updated_at = now()
                WHERE id = %s
                """,
                (status, next_phase, error, repo_id),
            )


def set_repo_phase(repo_id: str, phase: str) -> None:
    with get_db() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                UPDATE repos
                SET phase = %s, updated_at = now()
                WHERE id = %s
                """,
                (phase, repo_id),
            )


def get_repo_by_github_url(github_url: str) -> dict | None:
    with get_db() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute("SELECT * FROM repos WHERE github_url = %s", (github_url,))
            row = cur.fetchone()
            return dict(row) if row else None


def reset_repo_for_reingest(repo_id: str) -> None:
    with get_db() as conn:
        with conn.cursor() as cur:
            cur.execute("DELETE FROM domains WHERE repo_id = %s", (repo_id,))
            cur.execute("DELETE FROM chunks WHERE repo_id = %s", (repo_id,))
            cur.execute(
                """
                UPDATE repos
                SET status = 'pending',
                    phase = 'pending',
                    error = NULL,
                    chunk_count = 0,
                    cluster_tree = NULL,
                    updated_at = now()
                WHERE id = %s
                """,
                (repo_id,),
            )


def fail_in_progress_repos() -> None:
    with get_db() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                UPDATE repos
                SET status = 'failed',
                    phase = 'failed',
                    error = 'Ingestion interrupted by server restart',
                    updated_at = now()
                WHERE status IN ('pending', 'ingesting')
                """
            )


def update_repo_chunk_count(repo_id: str, count: int) -> None:
    with get_db() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "UPDATE repos SET chunk_count = %s WHERE id = %s",
                (count, repo_id),
            )


def get_repo(repo_id: str) -> dict | None:
    with get_db() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute("SELECT * FROM repos WHERE id = %s", (repo_id,))
            row = cur.fetchone()
            return dict(row) if row else None

def get_latest_ready_repo() -> dict | None:
    """Return the most recently updated repo with status=ready, or None."""
    with get_db() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(
                """
                SELECT id, name, status, chunk_count
                FROM repos
                WHERE status = 'ready'
                ORDER BY updated_at DESC
                    LIMIT 1
                """
            )
            row = cur.fetchone()
            return dict(row) if row else None


# ---------------------------------------------------------------------------
# Ingest quota helpers
# ---------------------------------------------------------------------------

def count_ingests_today(ip: str) -> int:
    """Count how many repos this IP has ingested in the last rolling 24 hours."""
    with get_db(register_vectors=False) as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT COUNT(*)
                FROM repo_ingest_log
                WHERE ip_address = %s
                  AND ingested_at > NOW() - INTERVAL '24 hours'
                """,
                (ip,),
            )
            return int(cur.fetchone()[0])


def log_ingest(ip: str, repo_id: str) -> None:
    """Record a new ingest for this IP."""
    with get_db(register_vectors=False) as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO repo_ingest_log (ip_address, repo_id)
                VALUES (%s, %s)
                """,
                (ip, repo_id),
            )


def has_recent_ingest_for_repo(ip: str, repo_id: str) -> bool:
    """Return whether this IP already ingested this repo in the rolling 24-hour window."""
    with get_db(register_vectors=False) as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT 1
                FROM repo_ingest_log
                WHERE ip_address = %s
                  AND repo_id = %s
                  AND ingested_at > NOW() - INTERVAL '24 hours'
                LIMIT 1
                """,
                (ip, repo_id),
            )
            return cur.fetchone() is not None


# ---------------------------------------------------------------------------
# Chunk helpers
# ---------------------------------------------------------------------------

def insert_chunk(repo_id: str, chunk: dict) -> str:
    """Insert one chunk row and return its UUID."""
    with get_db() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO chunks (
                    repo_id, file_path, file_type, language,
                    raw_code, summary, start_line, end_line,
                    loc, is_split, chunk_index
                ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
                RETURNING id
                """,
                (
                    repo_id,
                    chunk["file_path"],
                    chunk["file_type"],
                    chunk.get("language"),
                    chunk["content"],
                    chunk.get("summary"),
                    chunk.get("start_line"),
                    chunk.get("end_line"),
                    chunk.get("loc"),
                    chunk.get("is_split", False),
                    chunk.get("chunk_index", 0),
                ),
            )
            return str(cur.fetchone()[0])


def insert_chunks_batch(repo_id: str, chunks: list[dict]) -> list[str]:
    """
    Insert many chunks in one round trip.
    Returns list of UUIDs in the same order as input.
    """
    with get_db() as conn:
        with conn.cursor() as cur:
            records = [
                (
                    repo_id,
                    c["file_path"], c["file_type"], c.get("language"),
                    c["content"], c.get("summary"),
                    c.get("start_line"), c.get("end_line"),
                    c.get("loc"), c.get("is_split", False), c.get("chunk_index", 0),
                )
                for c in chunks
            ]
            psycopg2.extras.execute_values(
                cur,
                """
                INSERT INTO chunks (
                    repo_id, file_path, file_type, language,
                    raw_code, summary, start_line, end_line,
                    loc, is_split, chunk_index
                ) VALUES %s RETURNING id
                """,
                records,
            )
            return [str(row[0]) for row in cur.fetchall()]


# ---------------------------------------------------------------------------
# Vector helpers
# ---------------------------------------------------------------------------

def insert_vector(
    chunk_id: str,
    repo_id: str,
    summary_vector: list[float] | None,
    code_vector: list[float] | None,
) -> str:
    """Insert one vector row and return its UUID."""
    with get_db() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO vectors (chunk_id, repo_id, summary_vector, code_vector)
                VALUES (%s, %s, %s, %s)
                RETURNING id
                """,
                (chunk_id, repo_id, summary_vector, code_vector),
            )
            return str(cur.fetchone()[0])


def insert_vectors_batch(rows: list[dict]) -> None:
    """
    Insert many vector rows in one round trip.
    Each dict must have: chunk_id, repo_id, summary_vector, code_vector
    """
    with get_db() as conn:
        with conn.cursor() as cur:
            records = [
                (r["chunk_id"], r["repo_id"], r["summary_vector"], r["code_vector"])
                for r in rows
            ]
            psycopg2.extras.execute_values(
                cur,
                """
                INSERT INTO vectors (chunk_id, repo_id, summary_vector, code_vector)
                VALUES %s
                """,
                records,
            )


def update_vector_domain(chunk_ids: list[str], domain_id: str) -> None:
    """Assign a domain_id to a batch of vector rows after clustering."""
    with get_db() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                UPDATE vectors SET domain_id = %s::uuid
                WHERE chunk_id = ANY(%s::uuid[])
                """,
                (domain_id, chunk_ids),
            )


# ---------------------------------------------------------------------------
# RAG retrieval helpers
# ---------------------------------------------------------------------------

def search_summary_vectors(
    query_vector: list[float],
    repo_id: str,
    domain_id: str | None = None,
    top_k: int = 5,
) -> list[dict]:
    """
    Find top-k chunks by summary_vector cosine similarity.
    Optionally scoped to a specific domain.
    Returns list of dicts with chunk_id, file_path, summary, score.
    """
    with get_db() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            if domain_id:
                cur.execute(
                    """
                    WITH RECURSIVE scoped_domains AS (
                        SELECT id
                        FROM domains
                        WHERE id = %s::uuid AND repo_id = %s::uuid
                        UNION ALL
                        SELECT d.id
                        FROM domains d
                        JOIN scoped_domains sd ON d.parent_id = sd.id
                        WHERE d.repo_id = %s::uuid
                    )
                    SELECT
                        c.id AS chunk_id,
                        c.file_path,
                        c.summary,
                        c.raw_code,
                        v.domain_id,
                        1 - (v.summary_vector <=> %s::vector) AS score
                    FROM vectors v
                    JOIN chunks c ON c.id = v.chunk_id
                    WHERE v.repo_id = %s
                      AND v.domain_id IN (SELECT id FROM scoped_domains)
                      AND v.summary_vector IS NOT NULL
                    ORDER BY v.summary_vector <=> %s::vector
                    LIMIT %s
                    """,
                    (domain_id, repo_id, repo_id, query_vector, repo_id, query_vector, top_k),
                )
            else:
                cur.execute(
                    """
                    SELECT
                        c.id AS chunk_id,
                        c.file_path,
                        c.summary,
                        c.raw_code,
                        v.domain_id,
                        1 - (v.summary_vector <=> %s::vector) AS score
                    FROM vectors v
                    JOIN chunks c ON c.id = v.chunk_id
                    WHERE v.repo_id = %s
                      AND v.summary_vector IS NOT NULL
                    ORDER BY v.summary_vector <=> %s::vector
                    LIMIT %s
                    """,
                    (query_vector, repo_id, query_vector, top_k),
                )
            return [dict(r) for r in cur.fetchall()]


def search_code_vectors(
    query_vector: list[float],
    repo_id: str,
    domain_id: str | None = None,
    top_k: int = 5,
) -> list[dict]:
    """
    Find top-k chunks by code_vector cosine similarity.
    Optionally scoped to a specific domain.
    """
    with get_db() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            if domain_id:
                cur.execute(
                    """
                    WITH RECURSIVE scoped_domains AS (
                        SELECT id
                        FROM domains
                        WHERE id = %s::uuid AND repo_id = %s::uuid
                        UNION ALL
                        SELECT d.id
                        FROM domains d
                        JOIN scoped_domains sd ON d.parent_id = sd.id
                        WHERE d.repo_id = %s::uuid
                    )
                    SELECT
                        c.id AS chunk_id,
                        c.file_path,
                        c.summary,
                        c.raw_code,
                        v.domain_id,
                        1 - (v.code_vector <=> %s::vector) AS score
                    FROM vectors v
                    JOIN chunks c ON c.id = v.chunk_id
                    WHERE v.repo_id = %s
                      AND v.domain_id IN (SELECT id FROM scoped_domains)
                      AND v.code_vector IS NOT NULL
                    ORDER BY v.code_vector <=> %s::vector
                    LIMIT %s
                    """,
                    (domain_id, repo_id, repo_id, query_vector, repo_id, query_vector, top_k),
                )
            else:
                cur.execute(
                    """
                    SELECT
                        c.id AS chunk_id,
                        c.file_path,
                        c.summary,
                        c.raw_code,
                        v.domain_id,
                        1 - (v.code_vector <=> %s::vector) AS score
                    FROM vectors v
                    JOIN chunks c ON c.id = v.chunk_id
                    WHERE v.repo_id = %s
                      AND v.code_vector IS NOT NULL
                    ORDER BY v.code_vector <=> %s::vector
                    LIMIT %s
                    """,
                    (query_vector, repo_id, query_vector, top_k),
                )
            return [dict(r) for r in cur.fetchall()]


# ---------------------------------------------------------------------------
# Domain helpers
# ---------------------------------------------------------------------------

def insert_domain(
    repo_id: str,
    label: str,
    summary: str,
    level: int,
    chunk_ids: list[str],
    parent_id: str | None = None,
) -> str:
    """Insert one domain node and return its UUID."""
    with get_db() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO domains (repo_id, parent_id, label, summary, level, chunk_ids)
                VALUES (%s, %s, %s, %s, %s, %s::uuid[])
                    RETURNING id
                """,
                (repo_id, parent_id, label, summary, level, chunk_ids),
            )
            return str(cur.fetchone()[0])


def get_domain_tree(repo_id: str) -> list[dict]:
    """
    Fetch the full domain hierarchy for a repo as a flat list.
    Frontend builds the nested tree from parent_id references.
    """
    with get_db() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(
                """
                SELECT id, parent_id, label, summary, level, chunk_ids
                FROM domains
                WHERE repo_id = %s
                ORDER BY level, label
                """,
                (repo_id,),
            )
            return [dict(r) for r in cur.fetchall()]


def get_domain(domain_id: str) -> dict | None:
    """Fetch a single domain node by ID."""
    with get_db() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(
                "SELECT * FROM domains WHERE id = %s",
                (domain_id,),
            )
            row = cur.fetchone()
            return dict(row) if row else None
def store_cluster_tree(repo_id: str, tree: dict) -> None:
    """Store the full cluster tree as JSONB on the repo row."""
    import json
    with get_db() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                UPDATE repos
                SET cluster_tree = %s, updated_at = now()
                WHERE id = %s
                """,
                (json.dumps(tree), repo_id),
            )
